const CONNECTION = "connection";
const DISCONNECT = "disconnect";

const GET_CHAT = "GET_CHAT";
const CHAT_ERROR = "CHAT_ERROR";
const CHAT_MESSAGE = "CHAT_MESSAGE";

const JOIN_ACCESS = "JOIN_ACCESS";
const JOIN_ERROR = "JOIN_ERROR";
const GET_ROOMS = "GET_ROOMS";
const CREATE_SUCCESS = "CREATE_SUCCESS";
const CREATE_ERROR = "CREATE_ERROR";
const CREATE_ROOM = "CREATE";
const JOIN = "JOIN";
const JOIN_SUCCESS = "JOIN_SUCCESS";
const EXIT = "EXIT";

const ERROR_UPDATE_USER_ROOM = "ERROR_UPDATE_USER_ROOM";
const ERROR_DELETE_USER_ROOM = "ERROR_DELETE_USER_ROOM";
const ERROR_GET_USER_ROOMS = "ERROR_GET_USER_ROOMS";
const GET_ROOM = "GET_ROOM";
const GET_USER_ROOMS = "GET_USER_ROOMS";
const DELETE_USER_ROOM = "DELETE_USER_ROOM";
const UPDATE_USER_ROOM = "UPDATE_USER_ROOM";

const START_DRAW = "DRAW";
const CONNECTION_DRAW = "CONNECTION_DRAW";
const FINISH_DRAW = "FINISH_DRAW";
const CASE_EXIT = "CASE_EXIT";

const CHAT = {
  GET_CHAT,
  CHAT_MESSAGE,
  CHAT_ERROR
}
const ROOM = {
  GET_ROOMS,
  CREATE_ROOM,
  JOIN,
  JOIN_SUCCESS,
  JOIN_ACCESS,
  CREATE_SUCCESS,
  CREATE_ERROR,
  EXIT,
  JOIN_ERROR,
}
const USER_ROOM = {
  GET_ROOM,
  GET_USER_ROOMS,
  DELETE_USER_ROOM,
  UPDATE_USER_ROOM,
  ERROR_GET_USER_ROOMS,
  ERROR_DELETE_USER_ROOM,
  ERROR_UPDATE_USER_ROOM
}
const DRAW = {
  START_DRAW,
  CONNECTION_DRAW,
  FINISH_DRAW,
  CASE_EXIT
}
module.exports = { CONNECTION, DISCONNECT, CHAT, ROOM, USER_ROOM, DRAW };
