const CONNECTION = "connection";
const DISCONNECT = "disconnect";
const GET_CHAT = "GET_CHAT";
const GET_UPDATED_CHAT = 'GET_UPDATED_CHAT'
const CHAT_ERROR = "CHAT_ERROR";
const CHAT_MESSAGE = "CHAT_MESSAGE";
const JOIN_ACCESS = "JOIN_ACCESS";
const GET_ROOMS = "GET_ROOMS";
const CREATE_SUCCESS = "CREATE_SUCCESS";
const CREATE_ERROR = "CREATE_ERROR";
const CREATE_ROOM = "CREATE";
const EXIT = "EXIT";

const JOIN_ROOM = "JOIN";
const JOIN_ROOM_SUCCESS = "JOIN_SUCCESS";
const JOIN_ROOM_ERROR = "JOIN_ERROR";
const DELETE_USER_ROOM = "DELETE_USER_ROOM";
const DELETE_USER_ROOM_SUCCESS = "DELETE_USER_ROOM_SUCCESS";
const DELETE_USER_ROOM_ERROR = "DELETE_USER_ROOM_ERROR";
const UPDATE_USER_ROOM = "UPDATE_USER_ROOM";
const UPDATE_USER_ROOM_SUCCESS = "UPDATE_USER_ROOM_SUCCESS";
const UPDATE_USER_ROOM_ERROR = "UPDATE_USER_ROOM_ERROR";

const ERROR_GET_USER_ROOMS = "ERROR_GET_USER_ROOMS";
const GET_ROOM = "GET_ROOM";
const GET_USER_ROOMS = "GET_USER_ROOMS";

const START_DRAW = "DRAW";
const CONNECTION_DRAW = "CONNECTION_DRAW";
const FINISH_DRAW = "FINISH_DRAW";
const CASE_EXIT = "CASE_EXIT";
const GET_SNAPSHOT = "GET_SNAPSHOT";
const SEND_SNAPSHOT = "SEND_SNAPSHOT";
const SET_SNAPSHOT = "SET_SNAPSHOT";

const CHAT = {
  GET_CHAT,
  CHAT_MESSAGE,
  CHAT_ERROR,
  GET_UPDATED_CHAT
}
const ROOM = {
  GET_ROOMS,
  CREATE_ROOM,
  JOIN_ROOM,
  JOIN_ROOM_SUCCESS,
  JOIN_ACCESS,
  CREATE_SUCCESS,
  CREATE_ERROR,
  EXIT,
  JOIN_ROOM_ERROR,
}
const USER_ROOM = {
  GET_ROOM,
  GET_USER_ROOMS,
  DELETE_USER_ROOM,
  UPDATE_USER_ROOM,
  ERROR_GET_USER_ROOMS,
  DELETE_USER_ROOM_ERROR,
  UPDATE_USER_ROOM_ERROR,
  DELETE_USER_ROOM_SUCCESS,
  UPDATE_USER_ROOM_SUCCESS
}
const DRAW = {
  START_DRAW,
  CONNECTION_DRAW,
  FINISH_DRAW,
  CASE_EXIT,
  GET_SNAPSHOT,
  SEND_SNAPSHOT,
  SET_SNAPSHOT
}

module.exports = { CONNECTION, DISCONNECT, CHAT, ROOM, USER_ROOM, DRAW };
